
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aldiariq
 */
public class FormUtama extends javax.swing.JFrame {

    private JFileChooser filechooserFileenkripsi;
    private File fileAsli;
    private String lokasidannamafile;
    private File filesimpanKunci;
    private BufferedWriter bwsimpanKunci;
    private Enkripsi enkripsi;

    private JFileChooser filechooserFiledekripsi;
    private File fileEnkripsi;
    private String lokasidannamafileenkripsi;
    private BufferedReader brbacaKunci;
    private File fileKuncid;
    private String lokasidannamafilekuncid;
    private String Kuncid;
    private File fileKuncin;
    private String lokasidannamafilekuncin;
    private String Kuncin;
    private Dekripsi dekripsi;

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulaplikasi = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        tabEnkripsidekripsi = new javax.swing.JTabbedPane();
        pnlEnkripsi = new javax.swing.JPanel();
        lblTabenkripsi = new javax.swing.JLabel();
        btnEnkripsi = new javax.swing.JButton();
        btnSimpankunci = new javax.swing.JButton();
        btnUlangienkripsi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfieldLokasidannamafileenkripsi = new javax.swing.JTextField();
        btnPilihlokasidannamafileenkripsi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfieldP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfieldQ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfieldN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfieldTN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfieldE = new javax.swing.JTextField();
        tfieldD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfieldLokasidannamafilehasilenkripsi = new javax.swing.JTextField();
        pbEnkripsi = new javax.swing.JProgressBar();
        pnlDekripsi = new javax.swing.JPanel();
        lblTabdekripsi = new javax.swing.JLabel();
        btnDekripsi = new javax.swing.JButton();
        btnUlangidekripsi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfieldLokasidannamafiledekripsi = new javax.swing.JTextField();
        btnPilihlokasidannamafiledekripsi = new javax.swing.JButton();
        pbDekripsi = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        tfieldLokasidannamafilekuncid = new javax.swing.JTextField();
        btnPilihlokasidannamakuncid = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfieldLokasidannamafilekuncin = new javax.swing.JTextField();
        btnPilihlokasidannamakuncin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Utama");
        setResizable(false);

        lblJudulaplikasi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblJudulaplikasi.setText("Enkripsi dan Dekripsi File dengan Algoritma RSA");

        btnKeluar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        lblTabenkripsi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTabenkripsi.setText("Proses Enkripsi File");

        btnEnkripsi.setText("Mulai Enkripsi");
        btnEnkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnkripsiActionPerformed(evt);
            }
        });

        btnSimpankunci.setText("Simpan Kunci");
        btnSimpankunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpankunciActionPerformed(evt);
            }
        });

        btnUlangienkripsi.setText("Ulangi Enkripsi");
        btnUlangienkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangienkripsiActionPerformed(evt);
            }
        });

        jLabel1.setText("Lokasi & Nama File");

        tfieldLokasidannamafileenkripsi.setText("Lokasi & Nama File");
        tfieldLokasidannamafileenkripsi.setEnabled(false);

        btnPilihlokasidannamafileenkripsi.setText("Pilih File");
        btnPilihlokasidannamafileenkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihlokasidannamafileenkripsiActionPerformed(evt);
            }
        });

        jLabel2.setText("P");

        tfieldP.setText("P");

        jLabel3.setText("Q");

        tfieldQ.setText("Q");

        jLabel4.setText("N");

        tfieldN.setText("N");

        jLabel5.setText("TN");

        tfieldTN.setText("TN");

        jLabel6.setText("E");

        tfieldE.setText("E");

        tfieldD.setText("D");

        jLabel7.setText("D");

        jLabel8.setText("Lokasi & Nama File Hasil Enkripsi");

        tfieldLokasidannamafilehasilenkripsi.setText("Lokasi & Nama File Hasil Enkripsi");
        tfieldLokasidannamafilehasilenkripsi.setEnabled(false);

        pbEnkripsi.setString("50%");

        javax.swing.GroupLayout pnlEnkripsiLayout = new javax.swing.GroupLayout(pnlEnkripsi);
        pnlEnkripsi.setLayout(pnlEnkripsiLayout);
        pnlEnkripsiLayout.setHorizontalGroup(
            pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pbEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                            .addGap(259, 259, 259)
                            .addComponent(lblTabenkripsi))
                        .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEnkripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                                    .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfieldN, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfieldP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfieldE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfieldTN, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfieldD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfieldLokasidannamafilehasilenkripsi))
                                        .addComponent(btnSimpankunci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUlangienkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnkripsiLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(tfieldLokasidannamafileenkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPilihlokasidannamafileenkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlEnkripsiLayout.setVerticalGroup(
            pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnkripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabenkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfieldLokasidannamafileenkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihlokasidannamafileenkripsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnkripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbEnkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfieldP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfieldTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfieldE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfieldLokasidannamafilehasilenkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpankunci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUlangienkripsi)
                .addContainerGap())
        );

        tabEnkripsidekripsi.addTab("Enkripsi", pnlEnkripsi);

        lblTabdekripsi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTabdekripsi.setText("Proses Dekripsi File");

        btnDekripsi.setText("Mulai Dekripsi");
        btnDekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDekripsiActionPerformed(evt);
            }
        });

        btnUlangidekripsi.setText("Ulangi Dekripsi");
        btnUlangidekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangidekripsiActionPerformed(evt);
            }
        });

        jLabel9.setText("Lokasi & Nama File");

        tfieldLokasidannamafiledekripsi.setText("Lokasi & Nama File");
        tfieldLokasidannamafiledekripsi.setEnabled(false);

        btnPilihlokasidannamafiledekripsi.setText("Pilih File");
        btnPilihlokasidannamafiledekripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihlokasidannamafiledekripsiActionPerformed(evt);
            }
        });

        jLabel10.setText("Lokasi Kunci D");

        tfieldLokasidannamafilekuncid.setText("Lokasi Kunci D");
        tfieldLokasidannamafilekuncid.setEnabled(false);

        btnPilihlokasidannamakuncid.setText("Pilih File");
        btnPilihlokasidannamakuncid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihlokasidannamakuncidActionPerformed(evt);
            }
        });

        jLabel11.setText("Lokasi Kunci N");

        tfieldLokasidannamafilekuncin.setText("Lokasi Kunci N");
        tfieldLokasidannamafilekuncin.setEnabled(false);

        btnPilihlokasidannamakuncin.setText("Pilih File");
        btnPilihlokasidannamakuncin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihlokasidannamakuncinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDekripsiLayout = new javax.swing.GroupLayout(pnlDekripsi);
        pnlDekripsi.setLayout(pnlDekripsiLayout);
        pnlDekripsiLayout.setHorizontalGroup(
            pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDekripsiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTabdekripsi)
                .addGap(249, 249, 249))
            .addGroup(pnlDekripsiLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUlangidekripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlDekripsiLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfieldLokasidannamafilekuncin, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPilihlokasidannamakuncin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDekripsiLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfieldLokasidannamafilekuncid, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPilihlokasidannamakuncid, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnDekripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDekripsiLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(30, 30, 30)
                            .addComponent(tfieldLokasidannamafiledekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPilihlokasidannamafiledekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pbDekripsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlDekripsiLayout.setVerticalGroup(
            pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDekripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabdekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfieldLokasidannamafiledekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihlokasidannamafiledekripsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfieldLokasidannamafilekuncid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihlokasidannamakuncid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDekripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfieldLokasidannamafilekuncin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihlokasidannamakuncin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDekripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbDekripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUlangidekripsi)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        tabEnkripsidekripsi.addTab("Dekripsi", pnlDekripsi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tabEnkripsidekripsi)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblJudulaplikasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJudulaplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabEnkripsidekripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnPilihlokasidannamafileenkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihlokasidannamafileenkripsiActionPerformed
        // TODO add your handling code here:
        try {
            this.filechooserFileenkripsi = new JFileChooser();
            this.filechooserFileenkripsi.showOpenDialog(null);
            this.fileAsli = filechooserFileenkripsi.getSelectedFile();
            this.lokasidannamafile = fileAsli.getAbsolutePath();
            this.tfieldLokasidannamafileenkripsi.setText(lokasidannamafile);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(FormUtama.this, "File Belum Dipilih!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPilihlokasidannamafileenkripsiActionPerformed

    private void btnPilihlokasidannamakuncidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihlokasidannamakuncidActionPerformed
        // TODO add your handling code here:
        try {
            this.filechooserFiledekripsi = new JFileChooser();
            this.filechooserFiledekripsi.showOpenDialog(null);
            this.fileKuncid = filechooserFiledekripsi.getSelectedFile();
            this.lokasidannamafilekuncid = fileKuncid.getAbsolutePath();
            this.tfieldLokasidannamafilekuncid.setText(lokasidannamafilekuncid);

            try {
                this.brbacaKunci = new BufferedReader(new FileReader(fileKuncid));
                this.Kuncid = this.brbacaKunci.readLine();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(FormUtama.this, "File Belum Dipilih!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(FormUtama.this, "File Belum Dipilih!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPilihlokasidannamakuncidActionPerformed

    private void btnEnkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnkripsiActionPerformed
        try {
            this.enkripsi = new Enkripsi(fileAsli);
            this.setVariabelrsa(enkripsi.getP().toString(), enkripsi.getQ().toString(), enkripsi.getN().toString(), enkripsi.getTn().toString(), enkripsi.getE().toString(), enkripsi.getD().toString(), enkripsi.getLokasiFileDekripsi());
            Thread thread = new Thread() {
                @Override
                public void run() {
                    try {
                        for (int i = 1; i <= 100; i++) {
                            pbEnkripsi.setValue(i);
                            sleep(50);
                        }
                        JOptionPane.showMessageDialog(FormUtama.this, "Proses Enkripsi Selesai!", "Keterangan", JOptionPane.DEFAULT_OPTION);
                    } catch (InterruptedException ex) {
                    }
                }
            };
            thread.start();
        } catch (IOException | NullPointerException ex) {
            JOptionPane.showMessageDialog(FormUtama.this, "File Belum Dipilih!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnEnkripsiActionPerformed

    private void btnSimpankunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpankunciActionPerformed
        // TODO add your handling code here:
        try {
            this.simpanKunci("P", this.enkripsi.getP().toString());
            this.simpanKunci("Q", this.enkripsi.getQ().toString());
            this.simpanKunci("N", this.enkripsi.getN().toString());
            this.simpanKunci("TN", this.enkripsi.getTn().toString());
            this.simpanKunci("E", this.enkripsi.getE().toString());
            this.simpanKunci("D", this.enkripsi.getD().toString());
            JOptionPane.showMessageDialog(FormUtama.this, "Kunci Berhasil Disimpan!", "Keterangan", JOptionPane.DEFAULT_OPTION);
        } catch (NullPointerException | IOException e) {
            JOptionPane.showMessageDialog(FormUtama.this, "Anda Belum Mengenkripsi File", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpankunciActionPerformed

    private void btnUlangienkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangienkripsiActionPerformed
        // TODO add your handling code here:
        this.ulangiEnkripsi();
    }//GEN-LAST:event_btnUlangienkripsiActionPerformed

    private void btnPilihlokasidannamakuncinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihlokasidannamakuncinActionPerformed
        // TODO add your handling code here:
        try {
            this.filechooserFiledekripsi = new JFileChooser();
            this.filechooserFiledekripsi.showOpenDialog(null);
            this.fileKuncin = filechooserFiledekripsi.getSelectedFile();
            this.lokasidannamafilekuncin = fileKuncin.getAbsolutePath();
            this.tfieldLokasidannamafilekuncin.setText(lokasidannamafilekuncin);

            try {
                this.brbacaKunci = new BufferedReader(new FileReader(fileKuncin));
                this.Kuncin = this.brbacaKunci.readLine();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(FormUtama.this, "File Belum Dipilih!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            }
        } catch (HeadlessException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPilihlokasidannamakuncinActionPerformed

    private void btnPilihlokasidannamafiledekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihlokasidannamafiledekripsiActionPerformed
        // TODO add your handling code here:
        try {
            this.filechooserFiledekripsi = new JFileChooser();
            this.filechooserFiledekripsi.showOpenDialog(null);
            this.fileEnkripsi = filechooserFiledekripsi.getSelectedFile();
            this.lokasidannamafileenkripsi = fileEnkripsi.getAbsolutePath();
            this.tfieldLokasidannamafiledekripsi.setText(lokasidannamafileenkripsi);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(FormUtama.this, "File Belum Dipilih!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPilihlokasidannamafiledekripsiActionPerformed

    private void btnDekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDekripsiActionPerformed
        // TODO add your handling code here:
        if (this.Kuncid == null || this.Kuncin == null || this.fileEnkripsi == null) {
            JOptionPane.showMessageDialog(FormUtama.this, "Pastikan File Enkripsi dan Kunci Sudah Dipilih", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                BigInteger d = new BigInteger(this.Kuncid);
                BigInteger n = new BigInteger(this.Kuncin);

                this.dekripsi = new Dekripsi(d, n, this.fileEnkripsi);

                Thread thread = new Thread() {
                    @Override
                    public void run() {
                        try {
                            for (int i = 1; i <= 100; i++) {
                                pbDekripsi.setValue(i);
                                sleep(50);
                            }
                            JOptionPane.showMessageDialog(FormUtama.this, "Proses Enkripsi Selesai!", "Keterangan", JOptionPane.DEFAULT_OPTION);
                        } catch (InterruptedException ex) {
                        }
                    }
                };
                thread.start();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(FormUtama.this, "Pastikan File dan Kunci Enkripsi Sesuai!", "Kesalahan", JOptionPane.DEFAULT_OPTION);
            }
        }
    }//GEN-LAST:event_btnDekripsiActionPerformed

    private void btnUlangidekripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangidekripsiActionPerformed
        // TODO add your handling code here:
        this.fileEnkripsi = null;
        this.fileKuncid = null;
        this.fileKuncin = null;
        this.tfieldLokasidannamafiledekripsi.setText("Lokasi & Nama File");
        this.tfieldLokasidannamafilekuncid.setText("Lokasi Kunci D");
        this.tfieldLokasidannamafilekuncin.setText("Lokasi Kunci N");
        this.pbDekripsi.setValue(0);
    }//GEN-LAST:event_btnUlangidekripsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormUtama().setVisible(true);
        });
    }

    //Proses Set Nilai di Tampilan
    private void setVariabelrsa(String P, String Q, String N, String Tn, String E, String D, String File) {
        this.tfieldP.setText(P);
        this.tfieldQ.setText(Q);
        this.tfieldN.setText(N);
        this.tfieldTN.setText(Tn);
        this.tfieldE.setText(E);
        this.tfieldD.setText(D);
        this.tfieldLokasidannamafilehasilenkripsi.setText(File);
    }

    //Proses Mengosongkan Nilai dan Variabel
    private void ulangiEnkripsi() {
        this.tfieldP.setText("P");
        this.tfieldQ.setText("Q");
        this.tfieldN.setText("N");
        this.tfieldTN.setText("TN");
        this.tfieldE.setText("E");
        this.tfieldD.setText("D");
        this.tfieldLokasidannamafilehasilenkripsi.setText("Lokasi & Nama File Hasil Enkripsi");
        this.tfieldLokasidannamafileenkripsi.setText("Lokasi & Nama File");
        this.fileAsli = null;
        this.pbEnkripsi.setValue(0);
        this.enkripsi.setP(null);
        this.enkripsi.setQ(null);
        this.enkripsi.setN(null);
        this.enkripsi.setTn(null);
        this.enkripsi.setE(null);
        this.enkripsi.setD(null);
    }

    //Proses Penyimpanan Kunci
    private void simpanKunci(String jenisKunci, String Kunci) throws IOException {
        this.filesimpanKunci = new File("FolderOperasi/LokasiKunci/" + jenisKunci);
        try {
            this.bwsimpanKunci = new BufferedWriter(new FileWriter(filesimpanKunci));
            this.bwsimpanKunci.write(Kunci);
            this.bwsimpanKunci.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(FormUtama.this, "Pastikan Lokasi Penyimpanan Ada!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(FormUtama.this, "Pastikan Lokasi Penyimpanan Ada!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDekripsi;
    private javax.swing.JButton btnEnkripsi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPilihlokasidannamafiledekripsi;
    private javax.swing.JButton btnPilihlokasidannamafileenkripsi;
    private javax.swing.JButton btnPilihlokasidannamakuncid;
    private javax.swing.JButton btnPilihlokasidannamakuncin;
    private javax.swing.JButton btnSimpankunci;
    private javax.swing.JButton btnUlangidekripsi;
    private javax.swing.JButton btnUlangienkripsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblJudulaplikasi;
    private javax.swing.JLabel lblTabdekripsi;
    private javax.swing.JLabel lblTabenkripsi;
    private javax.swing.JProgressBar pbDekripsi;
    private javax.swing.JProgressBar pbEnkripsi;
    private javax.swing.JPanel pnlDekripsi;
    private javax.swing.JPanel pnlEnkripsi;
    private javax.swing.JTabbedPane tabEnkripsidekripsi;
    private javax.swing.JTextField tfieldD;
    private javax.swing.JTextField tfieldE;
    private javax.swing.JTextField tfieldLokasidannamafiledekripsi;
    private javax.swing.JTextField tfieldLokasidannamafileenkripsi;
    private javax.swing.JTextField tfieldLokasidannamafilehasilenkripsi;
    private javax.swing.JTextField tfieldLokasidannamafilekuncid;
    private javax.swing.JTextField tfieldLokasidannamafilekuncin;
    private javax.swing.JTextField tfieldN;
    private javax.swing.JTextField tfieldP;
    private javax.swing.JTextField tfieldQ;
    private javax.swing.JTextField tfieldTN;
    // End of variables declaration//GEN-END:variables
}
